# Generated by Django 2.2.2 on 2019-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField(blank=True)),
                ('ref_id', models.IntegerField()),
                ('headline', models.CharField(max_length=400)),
                ('nda_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
