# Generated by Django 2.2.2 on 2019-07-15 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='contact_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
