# Generated by Django 2.2.2 on 2019-07-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_inquiry_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='zipcode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
