# Generated by Django 2.2.2 on 2019-07-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190715_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='ref_id',
            field=models.CharField(max_length=30),
        ),
    ]
